FROM nvidia/cuda:9.2-base-ubuntu18.04

ADD ./setup.py /tmp
ADD ./substratools /tmp/substratools
ADD ./README.md /tmp

RUN apt-get update; \
    apt-get install -y python3-minimal python3-pip; \
    cd /tmp && pip3 install . ; \
    apt-get remove -y python3-pip --purge --autoremove; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/

RUN mkdir -p /sandbox
ENV PYTHONPATH /sandbox

WORKDIR /sandbox
