name: Python

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  lint:
    name: Lint and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install tools
        run: pip install flake8
      - name: Lint
        run: flake8 substratools
      - name: Install substra-tools
        run: pip install -e '.[dev]'
      - name: Test
        run: |
          make test
